# Generated by Django 5.2.5 on 2025-12-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_options_remove_todo_due_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_daily',
            field=models.BooleanField(default=False, verbose_name='کار روزانه'),
        ),
    ]
