# Generated by Django 5.2.5 on 2026-01-06 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_flashcard_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashLeitner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=512)),
                ('meaning', models.CharField(max_length=512)),
                ('example', models.CharField(blank=True, max_length=1024, null=True)),
                ('rate', models.SmallIntegerField(default=0)),
                ('last_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_review_date', models.DateField()),
                ('start_day', models.DateField(default=django.utils.timezone.localdate)),
            ],
        ),
    ]
