# Generated by Django 5.2.5 on 2025-11-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('start_day', models.DateField(auto_now_add=True)),
                ('one', models.DateField()),
                ('two', models.DateField()),
                ('seven', models.DateField()),
                ('month', models.DateField()),
                ('year', models.DateField()),
            ],
        ),
    ]
