# Generated by Django 5.2.5 on 2025-11-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='month',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='one',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='seven',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='two',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='year',
            field=models.BooleanField(default=False),
        ),
    ]
