# Generated by Django 5.2.5 on 2026-01-05 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_date', '0002_alter_reminder_month_alter_reminder_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='start_day',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
